Repository donggukthon/donggukthon_2023_4_B, pull requests merged in 2023-12, with the labels that each got.

#2 ✨ [Feat] Security설정과 소셜로그인을 구현한다.
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/donggukthon/volunmate/VolunmateApplication.java
  src/main/java/donggukthon/volunmate/annotation/SocialId.java
  src/main/java/donggukthon/volunmate/config/CorsConfig.java
  src/main/java/donggukthon/volunmate/config/SecurityConfig.java
  src/main/java/donggukthon/volunmate/config/SwaggerConfig.java
  src/main/java/donggukthon/volunmate/config/WebMvcConfig.java
  src/main/java/donggukthon/volunmate/constant/Constants.java
  src/main/java/donggukthon/volunmate/controller/AuthController.java
  src/main/java/donggukthon/volunmate/controller/HealthController.java
  src/main/java/donggukthon/volunmate/domain/User.java
  src/main/java/donggukthon/volunmate/dto/auth/AuthSignupDto.java
  src/main/java/donggukthon/volunmate/dto/exception/ArgumentNotValidExceptionDto.java
  src/main/java/donggukthon/volunmate/dto/exception/ExceptionDto.java
  src/main/java/donggukthon/volunmate/dto/exception/ResponseDto.java
  src/main/java/donggukthon/volunmate/dto/jwt/JwtTokenDto.java
  src/main/java/donggukthon/volunmate/exception/CustomException.java
  src/main/java/donggukthon/volunmate/exception/ErrorCode.java
  src/main/java/donggukthon/volunmate/exception/GlobalExceptionHandler.java
  src/main/java/donggukthon/volunmate/interceptor/SocialIdArgumentResolver.java
  src/main/java/donggukthon/volunmate/interceptor/SocialIdInterceptor.java
  src/main/java/donggukthon/volunmate/repository/UserRepository.java
  src/main/java/donggukthon/volunmate/security/CustomUserDetails.java
  src/main/java/donggukthon/volunmate/security/filter/JwtAuthenticationFilter.java
  src/main/java/donggukthon/volunmate/security/filter/JwtExceptionFilter.java
  src/main/java/donggukthon/volunmate/security/handler/JwtAccessDeniedHandler.java
  src/main/java/donggukthon/volunmate/security/handler/JwtEntryPoint.java
  src/main/java/donggukthon/volunmate/security/jwt/JwtProvider.java
  src/main/java/donggukthon/volunmate/security/service/CustomUserDetailsService.java
  src/main/java/donggukthon/volunmate/service/OAuth2Service.java
  src/main/java/donggukthon/volunmate/type/ELoginProvider.java
  src/main/java/donggukthon/volunmate/type/EUserType.java
  src/main/java/donggukthon/volunmate/utils/CookieUtil.java
  src/main/java/donggukthon/volunmate/utils/GoogleOAuth2Util.java
  src/main/java/donggukthon/volunmate/utils/JwtUtil.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement, feature

#19 fix : 위치기반 정렬 변경
  build.gradle
  src/main/java/donggukthon/volunmate/controller/HelpController.java
  src/main/java/donggukthon/volunmate/repository/HelpRepository.java
  src/main/java/donggukthon/volunmate/repository/VolunteerRepository.java
  src/main/java/donggukthon/volunmate/utils/GeometryUtil.java
Labels: fix

#20 [Fix] VolunteerController에서 봉사활동을 등록할 때, 이미지는 nullable이다.
  build.gradle
  src/main/java/donggukthon/volunmate/controller/VolunteerController.java
Labels: fix

#22 ✨ [Feat] 유저 정보를 수정하는 기능을 추가한다
  src/main/java/donggukthon/volunmate/controller/MyPageController.java
  src/main/java/donggukthon/volunmate/domain/User.java
  src/main/java/donggukthon/volunmate/dto/myPage/request/UserLocationDto.java
  src/main/java/donggukthon/volunmate/service/MyPageService.java
Labels: feature
